package enums;

public enum MessageType {
    CREATE_PLAYER_REQUEST,
    CREATE_PLAYER_SUCCESS,
    CREATE_LOBBY_REQUEST,
    CREATE_LOBBY_SUCCESS,
    JOIN_LOBBY_REQUEST,
    JOIN_LOBBY_SUCCESS,
    GET_QUESTION_REQUEST,
    GET_QUESTION_SUCCESS,
    CHECK_ANSWER_REQUEST,
    CHECK_ANSWER_SUCCESS,
    START_GAME_REQUEST,
    START_GAME_SUCCESS,
    END_GAME_REQUEST,
    END_GAME_SUCCESS,
    HOST_DISCONNECTED,
    NON_HOST_DISCONNECTED,
    NEXT_QUESTION_REQUEST,
    NEXT_QUESTION_SUCCESS,
    GAME_ENDED,
    ANSWER_CORRECT,
    ANSWER_INCORRECT,
    ERROR

}

// TODO 1: a lot of types to create...
